# Data Cleaning & Preparation

Before performing funnel analysis, the data must be cleaned and standardized.
The goal of this notebook is to ensure that:
- Missing or ambiguous values are handled properly
- The target variable is ready for analysis
- The dataset is suitable for visualization and dashboarding

In [1]:
# Importing the libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("bank-full.csv", sep=";")

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [3]:
# Check for actual null values
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

- The UCI Bank Marketing dataset does not use standard null values.
- Instead, missing or unavailable information is represented as the string `"unknown"`.

To handle this correctly, these values will be converted to NaN.

In [4]:
# Creating a clean copy of the dataset
df_clean = df.copy()

In [5]:
# Replace 'unknown' values with NaN
df_clean.replace("unknown", np.nan, inplace=True)

In [6]:
# Verify missing values after replacement
df_clean.isnull().sum()

age              0
job            288
marital          0
education     1857
default          0
balance          0
housing          0
loan             0
contact      13020
day              0
month            0
duration         0
campaign         0
pdays            0
previous         0
poutcome     36959
y                0
dtype: int64

In [7]:
# Identifying categorical columns
categorical_columns = df_clean.select_dtypes(include="object").columns

# Checking the number of unique values in each categorical column
for col in categorical_columns:
    print(f"{col}: {df_clean[col].nunique()} unique values")

job: 11 unique values
marital: 3 unique values
education: 3 unique values
default: 2 unique values
housing: 2 unique values
loan: 2 unique values
contact: 2 unique values
month: 12 unique values
poutcome: 3 unique values
y: 2 unique values

In [8]:
# Creating a binary version of the target variable
# 1 = conversion, 0 = no conversion

df_clean["y_binary"] = df_clean["y"].map({"yes": 1, "no": 0})

df_clean[["y", "y_binary"]].head()

    y  y_binary
0  no         0
1  no         0
2  no         0
3  no         0
4  no         0

Creating a binary target variable simplifies:
- Conversion rate calculations
- Funnel metrics
- Dashboard KPI creation

The original `y` column is preserved for interpretability.

In [9]:
# Check age distribution
df_clean["age"].describe()

count    45211.000000
mean        40.936210
std         10.618762
min         18.000000
25%         33.000000
50%         39.000000
75%         48.000000
max         95.000000
Name: age, dtype: float64

In [10]:
# Check campaign call frequency
df_clean["campaign"].describe()

count    45211.000000
mean         2.763841
std          3.098021
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         63.000000
Name: campaign, dtype: float64

Extremely high values in the `campaign` column may indicate
customer fatigue caused by excessive contact attempts.

This insight will be useful later when analyzing conversion drop-offs.

In [12]:
# Saved the cleaned dataset for further analysis and dashboard use

df_clean.to_csv("bank_marketing_cleaned.csv", index=False)
df_clean.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,y_binary
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no,0
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no,0
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no,0
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no,0

### Data Cleaning Summary

- Converted "unknown" values to NaN for transparency.
- Created a binary conversion flag for analytical flexibility.
- Preserved raw data integrity by saving a separate cleaned file.

The dataset is now ready for funnel and conversion analysis.